doc/index.md
src/windows/FileTransferProxy.js
tests/tests.js

This fixes [CB-8095](https://issues.apache.org/jira/browse/CB-8095)
On windows FileTrasfer doesn't support progress events for upload operation properly since internal implementation uses XHR which doesn't provide all information, necessary to fire correct progress events.
This PR replaces XHR with `BackgroundUploader` class which itself supports progress notification in more convenient way and can provide all necessary data for progress events for FileTransfer.

CB-8095 Adds support for progress events to upload operation

---

src/windows/FileTransferProxy.js

JIRA issue [CB-8407](https://issues.apache.org/jira/browse/CB-8407)
download() in file-transfer plugin expects path instead of internal URL on windows
This bug seems to be introduced with these changes to cordova-plugin-file: https://github.com/apache/cordova-plugin-file/commit/bcbeae24cd24583b790da95e0e076492eb16cd4f
All tests for download method of file-transfer plugin now fail on windows with following message:
```
Exception calling native with command :: FileTransfer :: download ::exception=WinRTError: The parameter is incorrect.
```

CB-8407 Fix downloading of ms-appdata:/// urls on Windows

---

src/android/FileTransfer.java

Fixes a small problem where an error was reported with the wrong uri when the sourceUri is invalid.

android: Fix error reporting for unknown uri type on sourceUri

---

src/wp/FileTransfer.cs

This is a quick fix for a crash described here: https://issues.apache.org/jira/browse/CB-8951
More in-depth approach can be found here:
https://github.com/apache/cordova-plugin-file-transfer/pull/72
but it is being delayed until wp8@4.0.0 release

CB-8951 Fixed crash related to headers parsing on wp8

---

src/windows/FileTransferProxy.js

Using a windows path raises an error. This fixes it by replacing all slashes in windows path instead of just the first one.

CB-8931 Replace all slashes in windows path

---

src/wp/FileTransfer.cs
www/FileTransfer.js

This is a bugfix for [CB-8721](https://issues.apache.org/jira/browse/CB-8721) which replaces custom parding of headers being passed to native code as JSON objects with usage of DataContractSerializer.
This also fixes bug described in https://github.com/apache/cordova-wp8/pull/62 without any extra dependencies.

CB-8721 Fixes incorrect headers and upload params parsing on wp8

---

src/android/FileTransfer.java

This was causing the FileTransfer plugin to always use the fallback android.webkit.CookieManager.

Fix NoSuchMethodException looking up cookies.

---

README.md

The `httpMethod` option was duplicated as an upload option in
[04f088b6c906e0b74bf3610005787b90aa548b9e](https://github.com/apache/cordova-plugin-file-transfer/commit/04f088b6c906e0b74bf3610005787b90aa548b9e)

README :: remove duplicate httpMethod option.

---

tests/tests.js

Also changes `toNativeURL` -> `toURL` because of deprecation.
[Jira issue](https://issues.apache.org/jira/browse/CB-9493)

CB-9493 Fix file paths in file-transfer manual tests

---

tests/tests.js

filetransfer.spec.6 was failing in 4.x branch of iOS because -1 was returned as length in a progress event.  Modified the test to look for <1 instead of == 0

Failing iOS 4.0 test

---

src/windows/FileTransferProxy.js
tests/tests.js

Adds a test for upload via PUT method
Adds support for Windows platform
[Jira issue](https://issues.apache.org/jira/browse/CB-51)

CB-51 API: FileTransfer - Support PUT Method

---

src/ios/CDVFileTransfer.h
src/ios/CDVFileTransfer.m
src/windows/FileTransferProxy.js
tests/tests.js

Adds support of 304 handling for iOS, Windows and adds a corresponding test.
[Jira issue](https://issues.apache.org/jira/browse/CB-6928)

CB-6928 Wrong behaviour transferring cacheable content

---

src/ios/CDVFileTransfer.m
src/windows/FileTransferProxy.js
tests/tests.js

Adds a corresponding test and fixes for iOS and Windows.
[Jira issue](https://issues.apache.org/jira/browse/CB-9969)
Also fixes `filetransfer.spec.9`, which used an incorrect path in the `root.getFile` call.

CB-9969 Filetransfer upload error deletes original file

---

README.md

Documents supported params key/value type
[Jira issue](https://issues.apache.org/jira/browse/CB-9600)

CB-9600 FileUploadOptions params not posted on iOS

---

README.md
src/ios/CDVFileTransfer.m
src/windows/FileTransferProxy.js
tests/tests.js

Adds iOS and Windows implementation; mention in the docs
Adds corresponding tests
Increases spec.35 timeout for Windows Phone 8.1 case as it contains 2 download operations (it was occasionally failing on device)
[Jira issue](https://issues.apache.org/jira/browse/CB-9837)

CB-9837 Add data URI support to file-transfer upload on iOS

---

tests/tests.js

The expectation in this spec is causing the crash in the build process. The error message is "Expected Spy but got a function". This error will happen only if there is no spy on the function. But as you can see the spy is set and still we get the error. 
In order to avoid the error, I am commenting out this expectation. I do not think this would have any adverse impact as we do check for the error code (to be aborted)  and the presence of the file(the purpose of this spec). So, I am confident that we are not losing any functionality by commenting out this expectation. 
@rakatyal @riknoll @omefire Can you please review and merge this PR?

Removing the expectation in spec.34 for the transfer method to be called

---

README.md
src/android/FileTransfer.java
src/ios/CDVFileTransfer.h
src/ios/CDVFileTransfer.m
tests/tests.js

Fixed iOS logic to not to include Content-Length when chunkedMode=true
Fixed Android logic preventing chunkedMode to be enabled for http uploads
Added tests for chunkedMode
Documented chunkedMode not supported on Windows
Documented Uploading of an empty file is not supported for chunkedMode=true and multipart=false for iOS, pended the corresponding test
[Jira issue](https://issues.apache.org/jira/browse/CB-10974)

CB-10974 Cordova file transfer Content-Length header problem

---

tests/tests.js

All
Replaces external Apache resource to cordova-vm one for HTTP 304 tests. This is needed to resolve intermittent spec 33 and 35 failures on iOS (see https://issues.apache.org/jira/browse/CB-11479 for details)
Ran autotests via paramedic on all main platforms

CB-11497 Use cordova-vm for testing 304 errors

---

tests/hooks/after_prepare.js
tests/plugin.xml
tests/tests.js

All
Allows tests to use a locally deployed server. You can specify its address via `--variable FILETRANSFER_SERVER_ADDRESS=http://your.address.here:5000` upon plugin installation.
The server itself can be found at:
https://github.com/apache/cordova-labs/tree/cordova-filetransfer
However, it's easier to just use paramedic, which can deploy this server and patch the tests to use it automatically:
https://github.com/apache/cordova-paramedic/pull/17
Tested w/ and w/o paramedic on Android and Windows platforms.

CB-11926 Tests can use local server

---

src/ios/CDVFileTransfer.m
tests/tests.js

iOS
Reverts logic for not setting `Content-Length` for `chunkedMode=true`.
This was causing progress events total to be -1 and progress to be not computable.
So while this change technically violates the [specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4) it fixes the functionality.
Manual and autotests.

CB-12154 file-transfer progressEvent.total = -1 on iOS

---

tests/tests.js

All
* Some tests now retry up to 100 times due to Heroku giving unstable results
* Now using '/upload_headers_echo' of the FT server instead of whatheaders.com which is down
https://issues.apache.org/jira/browse/CB-12439
20 runs on Android 4.4 emulator (Sauce Labs)

CB-12439 (Tests) Re-enable the tests

---

src/windows/FileTransferProxy.js

windows
Fix js error "The parameter is incorrect" when download progress is 0 in error handler
Manual testing

Fix js error "The parameter is incorrect"

---

src/ios/CDVFileTransfer.m

This closes #263
This closes #258
iOS
This solves the issue in #258 and makes the plugin compatible with cordova-ios@6.  
It also re-implements the user agent overwrite.
Sadly, there is no "nice" way to obtain the WKWebView user agent other than evaluating JavaScript.
My local fork compiles and has the correct user agent attached when making the network requests.

fix(ios): re-implement user agent overwrite

---

README.md

Removes references of an undefined loadingStatus object and replaces
it with comments or vanillaJS to improve clarity.
Documentation
Improves documentation readability.
Closes #206 
Replaces usages of an undefined `loadingStatus` object in favour of comments and/or vanillaJS.
N/A

doc: Improve progressEvent documentation

---

src/ios/CDVFileTransfer.m

iOS
The call to evaluateJavaScript is not blocking resulting in the headers
being set on the request after it is already sent.
fixes #285
Both the android and windows native code do not set the user-agent header.
The user can still set the user-agent header by sending it from javascript.
I've changed these lines in our application because our FileTransfer uses a `Authorization` header that was not being sent anymore.
After this change the request succeeds again.

fix(ios): headers are not being sent

---

src/ios/CDVFileTransfer.m

no other platform sets this header and it should be up to the user if it's desired to 'disguise' the HTTP call as an XMLHttpRequest

fix(ios): remove hardcoded X-Requested-With header

---

src/android/FileTransfer.java

Android
Build is failing in Cordova-Android 10.
fixes: #306
The `Whitelist` import can be removed.
The `getWhitelist` method was removed a long time ago. The `getWhitelist` method was related to the commented statement:
> This code exists for compatibility between 3.x and 4.x versions of Cordova.
The `AllowList` which was integrated into the core of **cordova-android** is still being loaded as if it was a plugin so there for the next if block should still work as usual to fetch the `shouldAllowRequest` value.
```java
if (shouldAllowRequest == null) {
try {
Method gpm = webView.getClass().getMethod("getPluginManager");
PluginManager pm = (PluginManager)gpm.invoke(webView);
Method san = pm.getClass().getMethod("shouldAllowRequest", String.class);
shouldAllowRequest = (Boolean)san.invoke(pm, …
```

feat!: remove deprecated whitelist usage

---

tests/tests.js

Asset file paths are incorrect and does not exist. This PR updates the paths to the actual location of the files.
- see GH Actions

test: fix asset file paths

---

src/android/FileTransfer.java

Android
On Android Q and above, the download functionality does not function.
This change enables use of FileOutputStream to save files into the download folder.
Without the changes, Android Q will fail to download, while on Android P and below it will work fine.
With the changes, Android Q and above will have no problems with downloads.
https://github.com/apache/cordova-plugin-file-transfer/issues/300
https://github.com/apache/cordova-plugin-file-transfer/issues/291

fix(android): enable download functionality with Android Q

---

.npmrc

N/A
Progresses https://github.com/apache/cordova/issues/299
Ensures that the official NPM registry is used when installing packages for contributors that uses a more complicated NPM environment configuration.

chore: .npmrc

---

package-lock.json

N/A
Regenerated package-lock using v2
Progresses https://github.com/apache/cordova/issues/300
Depends on https://github.com/apache/cordova-plugin-file-transfer/pull/323
ran npm test (failures due to eslint)

chore: package-lock upgrade

---

plugin.xml

Android
Remove the `use-permission` `WRITE_EXTERNAL_STORAGE`.
The plugins's dependency, cordova-plugin-file`, also sets this permission.
Remove `use-permission` settings
- `npm t`

chore(android): remove use-permission WRITE_EXTERNAL_STORAGE

---

package-lock.json
package.json
src/windows/FileTransferProxy.js
tests/hooks/after_prepare.js
tests/server/index.js
tests/tests.js
www/FileTransfer.js
www/FileTransferError.js
www/browser/FileTransfer.js

All
Depends on https://github.com/apache/cordova-plugin-file-transfer/pull/324
Upgrades and fixes ESlint errors
Upgrades Eslint to the latest cordova eslint config & applied the eslint fixes
Ran npm test successfully.

chore: eslint upgrade

---

package-lock.json
package.json
plugin.xml
tests/package.json

android
Use latest file plugin which resolves permission issues in Android 13+ (SDK 33) 
* Bump file plugin version to 8.0.0
* Added Cordova-Android requirement to >=12.0.0 which supports SDK 33.
`npm t`

feat(android)!: bump cordova-plugin-file@8.0.0 & cordova-android >= 12.0.0

---

package-lock.json
package.json

n/a
Update npm dependencies & rebuild package-lock
- Bump `@cordova/eslint-config@5.0.0`
- Rebuilt `package-lock.json`
`npm t`

dep: bump @cordova/eslint-config@5.0.0 w/ rebuilt package-lock

---

tests/server/index.js

port 5000 is taken by default on macOS monterrey and newer, use 5001
see https://github.com/apache/cordova-paramedic/pull/262

fix(tests): change default server port

---

tests/tests.js

Latest versions of cordova block http connections by default, change tests to use the equivalent https urls when available (there is no https url for techslides, but I don't think manual tests are run anyway).
Alternatively, we should make the test app to allow http connection.

fix(tests): Use https on file urls

---

tests/server/index.js

Add missing license header to the test server js file.

chore: add missing license header
