apache/cordova-plugin-file-transfer

doc/index.md
plugin.xml
tests/tests.js
www/browser/FileTransfer.js

Implementation for [CB-7957](https://issues.apache.org/jira/browse/CB-7957)

CB-7957 Adds support for `browser` platform

---

tests/tests.js

This is a fix for https://issues.apache.org/jira/browse/CB-8495

CB-8495 Fixed wp8 and wp81 test failures

---

src/windows/FileTransferProxy.js

This fixes [CB-8583](https://issues.apache.org/jira/browse/CB-8583)

CB-8583 Forces download to overwrite existing target file

---

src/wp/FileTransfer.cs
tests/tests.js

Reworked my previous fix attempt and also fixed more tests.
https://issues.apache.org/jira/browse/CB-8641

CB-8641 Fixed tests to pass on windows and wp8

---

tests/tests.js

https://issues.apache.org/jira/browse/CB-8933

CB-8933 Increased download and upload test timeout

---

tests/tests.js

https://issues.apache.org/jira/browse/CB-9791

CB-9791 Decreased download and upload tests timeout

---

tests/tests.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10037)

CB-10037 Add progress indicator to file-transfer manual tests

---

tests/tests.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10098)

CB-10098 filetransfer.spec.33 is faulty

---

src/windows/FileTransferProxy.js
tests/tests.js

Adds a corresponding test.
Fixes the Windows proxy to not to delete the file in case of 304.
As a side effect the new code will not delete a cached file (previously downloaded f.e.) in case of a download error.
The test is passing on Android and Windows (with this modification) and fails on iOS as code 200 comes for the second request disregarding the `If-Modified-Since` header, as soon as we get code 200 in the first request (the file is being cached by the iOS proxy somewhere).
@shazron, could you please point to where to look at in the iOS implementation for this caching?
[Jira issue](https://issues.apache.org/jira/browse/CB-7006)

CB-7006 Empty file is created on file transfer if server response is 304

---

src/windows/FileTransferProxy.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10208)

CB-10208 Fix file-transfer multipart form data upload format on Windows

---

.jscsrc
.jshintrc
.travis.yml
README.md
package.json
src/windows/FileTransferProxy.js
www/FileTransfer.js
www/blackberry10/.jshintrc
www/blackberry10/FileTransfer.js
www/blackberry10/xhrFileTransfer.js
www/browser/FileTransfer.js
www/firefoxos/FileTransferProxy.js
www/wp7/base64.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10636)

CB-10636 Add JSHint for plugins

---

tests/tests.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10978)

CB-10978 Fix file-transfer.tests JSHint issues

---

src/android/FileTransfer.java

Android
This PR fixes application crash when trying to upload file from 'Content' file system, specified by `cdvfile://localhost/content/...` URI.
Manual and automated testing
We should call `remapUri` on background thread otherwise it throws `IllegalStateException` when trying to remap  'cdvfile://localhost/content/...' URIs via `ContentFilesystem`

CB-9022 Resolve source URI on background thread

---

tests/tests.js

All
fixes the jshint issues in a previous commit
`jshint www && jshint src && jshint tests`

CB-11959 Fixed the jshint issues

---

src/ios/CDVFileTransfer.m
tests/tests.js

iOS
Encodes target path for downloading process
Auto-test

CB-10696 iOS: Encode target path with spaces

---

www/browser/FileTransfer.js

Found this bug when receiving a 201 response.

Fire successCallback for any 2XX HTTP status

---

.travis.yml

CB-13749: Add build-tools-26.0.2 to travis

---

README.md

docs: undeprecate the plugin

---

package.json
plugin.xml
tests/plugin.xml

chore: bump version to 2.0.0-dev

---

package.json
plugin.xml

chore: package cleanup

---

package.json

Package
New major version 2.0 to come.
Following initial add of 'protective' entry into _cordovaDependencies_ from #157
```
... On every major release we will need to add similar entry with next major version.
```
Fix #298

Bump 'protective' entry for major release 2.0 to come

---

.github/workflows/android.yml
.github/workflows/chrome.yml
.github/workflows/ios.yml
.github/workflows/lint.yml
tests/plugin.xml
tests/server/index.js
tests/server/package-lock.json
tests/server/package.json

Add GitHub Actions Workflow
* Custom steps were applied to this plugin as it requires a server.

ci: add gh-actions workflows

---

tests/package.json

Incorrect version in test package.json
Bumped test `package.json` version to match with plugin.xml and also the root `package.json`
`npm t`

fix: test version

---

tests/tests.js
www/FileTransfer.js

remove some windows and windows phone leftovers

chore: remove windows leftovers

---

tests/server/index.js
tests/server/package-lock.json
tests/server/package.json

n/a
Use latest dependencies for test server
bumped: 
- forever@4.0.3
- iconv@3.0.1
- busboy@1.6.0
Rebuilt package-lock.json
launched the test server.

dep(server)!: bump forever@4.0.3, iconv@3.0.1, busboy@1.6.0 & rebuilt package-lock
